version: '2'

services:
  slanger:
    build:
      context: .
    ports:
      - "8080:8080"
      - "4567:4567"
    links:
      - redis:redis

  redis:
    image: redis:latest
    expose:
      - "6379"
